apiVersion: v1
kind: Service
metadata:
  name: rancher-ms-service
  namespace: rancher-ms-ns
spec:
  selector:
    app: rancher-ms-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
