apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-deployment
  namespace: dog-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dog-app
  template:
    metadata:
      labels:
        app: dog-app
    spec:
      containers:
      - name: dog-container
        image: horowitzathome/rancher-ms
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
