apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: dog-ns
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>

    <label @FLUENT_LOG>
      <filter **>
        @type parser
        format json
        key_name ""
      </filter>

      <match **>
        @type stdout
      </match>
    </label>
    